# Basic Alacritty configuration in TOML format

[window]
dimensions = { columns = 100, lines = 30 }
padding = { x = 6, y = 6 }
opacity = 0.80
dynamic_title = true

[font]
size = 11.0

[scrolling]
history = 100000
multiplier = 5