name: Home Manager Standalone

on:
  workflow_dispatch:

jobs:
  test-home-manager:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Nix
      uses: cachix/install-nix-action@v23
      with:
        nix_path: nixpkgs=channel:nixos-24.11
        extra_nix_config: |
          experimental-features = nix-command flakes
          
    - name: Verify Nix Installation
      run: |
        nix --version
        nix-env --version
        nix-channel --list
        echo "NIX_PATH: $NIX_PATH"
        
    - name: Install Home Manager
      run: |
        # Use release-24.11 to match your nixpkgs version
        nix-channel --add https://github.com/nix-community/home-manager/archive/release-24.11.tar.gz home-manager
        nix-channel --update
        export NIX_PATH=$HOME/.nix-defexpr/channels:$NIX_PATH
        nix-shell '<home-manager>' -A install
        
    - name: Verify Home Manager Installation
      run: |
        export NIX_PATH=$HOME/.nix-defexpr/channels:$NIX_PATH
        which home-manager
        home-manager --version
        nix-channel --list | grep home-manager
        
    - name: Test Home Manager configuration using flake
      env:
        USER: "runner"
        CI: "true"  # Triggers conditional import exclusion
      run: |
        # Use auto@linux with CI detection
        home-manager switch --flake .#auto@ci -b backup
        
    - name: Verify Nix packages are installed
      run: |
        echo "Checking if git is from Nix store:"
        readlink $(which git) | grep -q "/nix/store" && echo "✓ Git is from Nix store" || echo "✗ Git is NOT from Nix store"
        
        echo "Checking starship installation:"
        readlink $(which starship) | grep -q "/nix/store" && echo "✓ Starship is from Nix store" || echo "✗ Starship is NOT from Nix store"
        
    - name: Final verification summary
      run: |
        echo $PATH | tr ':' '\n' | grep nix-profile || echo "No nix-profile in PATH"
        echo "Total packages installed by Home Manager:"
        ls -la ~/.nix-profile/bin/ | wc -l